// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SporSalonu.Data;

#nullable disable

namespace SporSalonu.Migrations
{
    [DbContext(typeof(SporContext))]
    [Migration("20260504141231_OlcumTabloGuncelleme")]
    partial class OlcumTabloGuncelleme
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SporSalonu.Models.AntrenmanProgramlari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bolge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gun")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HareketAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Set")
                        .HasColumnType("int");

                    b.Property<int>("Tekrar")
                        .HasColumnType("int");

                    b.Property<int>("UyeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UyeId");

                    b.ToTable("AntrenmanProgramlari", (string)null);
                });

            modelBuilder.Entity("SporSalonu.Models.BeslenmeProgramlari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kalori")
                        .HasColumnType("int");

                    b.Property<string>("OgunAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("UyeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UyeId");

                    b.ToTable("BeslenmeProgramlari");
                });

            modelBuilder.Entity("SporSalonu.Models.GirisKayitlari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("GirisZamani")
                        .HasColumnType("datetime2");

                    b.Property<int>("UyeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UyeId");

                    b.ToTable("GirisKayitlari");
                });

            modelBuilder.Entity("SporSalonu.Models.Kullanicilar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar", (string)null);
                });

            modelBuilder.Entity("SporSalonu.Models.Olcumler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("BelCevresi")
                        .HasColumnType("float");

                    b.Property<int>("Boy")
                        .HasColumnType("int");

                    b.Property<double?>("GogusCevresi")
                        .HasColumnType("float");

                    b.Property<double>("Kilo")
                        .HasColumnType("float");

                    b.Property<double?>("KolCevresi")
                        .HasColumnType("float");

                    b.Property<DateTime>("OlcumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("UyeId")
                        .HasColumnType("int");

                    b.Property<double?>("YagOrani")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("UyeId");

                    b.ToTable("Olcumler");
                });

            modelBuilder.Entity("SporSalonu.Models.Uyeler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GunlukKaloriHedefi")
                        .HasColumnType("int");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UyelikBitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("UyelikPaketiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UyelikPaketiId");

                    b.ToTable("Uyeler", (string)null);
                });

            modelBuilder.Entity("SporSalonu.Models.UyelikPaketleri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KacAylikPaket")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaketAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Ucret")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("UyelikPaketleri");
                });

            modelBuilder.Entity("SporSalonu.Models.AntrenmanProgramlari", b =>
                {
                    b.HasOne("SporSalonu.Models.Uyeler", "Uye")
                        .WithMany()
                        .HasForeignKey("UyeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uye");
                });

            modelBuilder.Entity("SporSalonu.Models.BeslenmeProgramlari", b =>
                {
                    b.HasOne("SporSalonu.Models.Uyeler", "Uye")
                        .WithMany()
                        .HasForeignKey("UyeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uye");
                });

            modelBuilder.Entity("SporSalonu.Models.GirisKayitlari", b =>
                {
                    b.HasOne("SporSalonu.Models.Uyeler", "Uye")
                        .WithMany("GirisKayitlari")
                        .HasForeignKey("UyeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uye");
                });

            modelBuilder.Entity("SporSalonu.Models.Olcumler", b =>
                {
                    b.HasOne("SporSalonu.Models.Uyeler", "Uye")
                        .WithMany()
                        .HasForeignKey("UyeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uye");
                });

            modelBuilder.Entity("SporSalonu.Models.Uyeler", b =>
                {
                    b.HasOne("SporSalonu.Models.UyelikPaketleri", "UyelikPaketi")
                        .WithMany("Uyeler")
                        .HasForeignKey("UyelikPaketiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UyelikPaketi");
                });

            modelBuilder.Entity("SporSalonu.Models.Uyeler", b =>
                {
                    b.Navigation("GirisKayitlari");
                });

            modelBuilder.Entity("SporSalonu.Models.UyelikPaketleri", b =>
                {
                    b.Navigation("Uyeler");
                });
#pragma warning restore 612, 618
        }
    }
}
